image sooneutralquiet = "images/sooneutralquiet.png"
image sooneutraltalk = "images/sooneutraltalk.png"
image soosmilequiet = "images/soosmilequiet.png"
image soosmiletalk = "images/soosmiletalk.png"

image jihoquiet = "images/Black haired blue eye boy/jihoquiet.png"
image jihoneutralquiet = "images/Black haired blue eye boy/jihoneutralquiet.png"
image jihotalking = "images/Black haired blue eye boy/jihohappytalking.png"
image jihoangrytalking = "images/Black haired blue eye boy/jihoangrytalking.png"
image jihosad = "images/Black haired blue eye boy/jihosad.png"
image jihocrying = "images/Black haired blue eye boy/jihocrying.png"
image jihosmiling = "images/Black haired blue eye boy/jihosmiling.png"
image jihointear = "images/Black haired blue eye boy/jihointear.png"
image jihosweating = "images/Black haired blue eye boy/jihosweating.png"
image jihoworried = "images/Black haired blue eye boy/jihoworried.png"

image wooquiet = "images/Blond hair blue eyed boy/wooquiet.png"
image wootalk = "images/Blond hair blue eyed boy/wootalk.png"
image woosmile = "images/Blond hair blue eyed boy/woosmiling.png"
image woosmiletalk = "images/Blond hair blue eyed boy/woosmiletalk.png"
image woodisturbed = "images/Blond hair blue eyed boy/woodisturbed.png"
image woosad = "images/Blond hair blue eyed boy/woosad.png"
image woocrying = "images/Blond hair blue eyed boy/woocrying.png"
image woointear = "images/Blond hair blue eyed boy/woointear.png"
image woosweating = "images/Blond hair blue eyed boy/woosweating.png"

image minhoquiet = "images/RBB/minhoquiet.png"
image minhotalk = "images/RBB/minhotalk.png"
image minhosmile = "images/RBB/minhosmile.png"
image minhosmiletalk = "images/RBB/minhosmiletalk.png"
image minhodisturbed = "images/RBB/minhodisturbed.png"
image minhoupset = "images/RBB/minhoupset.png"
image minhointear = "images/RBB/minhointear.png"

image eunhyeongquiet = "images/bbb/eunhyeongquiet.png"
image eunhyeongtalk = "images/bbb/eunhyeongtalk.png"
image eunhyeongsmile = "images/bbb/eunhyeongsmile.png"
image eunhyeonghappytalk = "images/bbb/eunhyeonghappytalk.png"
image eunhyeongdisturbed = "images/bbb/eunhyeongdisturbed.png"
image eunhyeongintear = "images/bbb/eunhyeongintear.png"
image eunhyeongneutral = "images/bbb/eunhyeongneutral.png"

image saraquiet = "images/BBG/saraquiet.png"
image saratalking = "images/BBG/saratalking.png"
image sarasmilequiet = "images/BBG/saraquiet.png"
image sarasmiletalk = "images/BBG/sarasmilingtalking.png"
image saraneutraltalk = "images/BBG/saratalking.png"
image saradisturbed = "images/BBG/saradisturbed.png"
image saracrying = "images/BBG/saracrying.png"
image saraintear = "images/BBG/saraintear.png"

image npcquiet = "images/npcquiet.png"
image npctalking = "images/npctalking.png"

image bg room = "images/background/room.jpg"
image bg hallway = "images/background/hallway.png"
image bg school = "images/background/school.png"
image bg floor = "images/background/floor.png"
image bg class = "images/background/school.png"
image bg school_hallway = "images/background/hallway.png"
image bg school_gate = "images/background/school.png"
image bg staff_room = "images/background/room.jpg"
