image sooneutralquiet = "images/sooneutralquiet.png"
image sooneutraltalk = "images/sooneutraltalk.png"
image soosmilequiet = "images/soosmilequiet.png"
image soosmiletalk = "images/soosmiletalk.png"
image saraneutraltalk = "images/saraneutraltalk.png"
image sarasmilequiet = "images/sarasmilequiet.png"
image sarasmiletalk = "images/sarasmiletalk.png"

image bg room = "images/background/room.png"
image bg hallway = "images/background/hallway.png"
image bg school = "images/background/school.png"
image bg floor = "images/background/floor.png"