label start:

    scene bg room

    "The morning of mt middle school entrance ceremony."

    soo "Soo-ah, 14 years old"
    soo "..."
    mom "Soo-ah, what are you going?"
    mom "You're going to be late."
    soo "Mom..."
    soo "Where's my school uniform?"
    mom "?"
    mom "What are you talking about?"
    soo "THIS ISN'T MY UNIFORM!"
    mom "WELL, THAT IS YOUR SCHOOL UNIFORM!"
    mom "WE WENT TOGETHER LAST WEEK TO GET IT FIT!"
    thought "Is.. Is this really my school uniform?"
    soo "Like a uniform that came straight out of a comic book or a novel!"
    thought "I would never wear this!"
    mom "So your'e not going to school?"
    scene bgidk
    thought "Am I dreaming? Or suffering from amnesia?"
    thought "I thought the school uniform was white?"
    show sarasmilequiet
    thought "...??"
    thought "Her skin is so pale and smooth."
    thought "Silky blond hair that falls down to her waist, like a waterfall."
    thought "Her clear eyes shining with such a lovely shade."
    thought "Such an unrealistic pretty girl is in front of me."
    thought "Wow~! She's so pretty!"
    thought "I've never seen her before, is she new here?"
    thought "Wait, what is she doing in front of my house?"
    thought "Was I staring at her for too long?"
    sara "Soo-ah, we're going to be late."
    sara "Let's go."
    thought "Oh my gosh..."
    thought "Her voice is so pretty."
    sara "Lets go~"
    soo "Okay!"
    thought "No wait!"
    soo "WAIT A MINUTE!"
    sara "Yes?"
    soo "What are we doing right now?"
    sara "What are-"
    sara "We are going to school!"
    thought "March 2nd, the day of the school entrance ceremony."
    thought "My daily life has begun to change into a web novel."
    thought "To think that such an unrealistic thing would happen to me."
    soo "Of course I'm going to school!"
    soo "But why do I have to go with you?"
    soo "Who on earth is she..?"
    thought "Sara Lee?"
    thought "It's my first time hearing that name...?"
    sara "I get it... I understand what you're trying to say, but..."
    sara "Let's go to school first."
    soo "Wait, what do you mean you understand..."
    thought "Wha, what. That heartbroken expression."
    show saradisturbed
    soo "O...Okay."
    thought "Did I actually lose my memory?"
    thought "Or is someone messing with me?"
    thought "..."
    thought "I must've been in a daze if I went along with her..."
    thought "I don't even know her! It's the first time I've ever seen her."
    thought "Huh?"
    thought "I've never seen this place before."
    sara "Soo-ah."
    soo "YE...YEAH?"
    sara "Ca... Can I hold your hand?"
    soo "Huh..?"
    soo "Sure?"
    thought "She's very pretty..."
    thought "I understand why everyone is staring at her..."
    thought "Being a girl's escort... is not that bad?"
    thought "Wha-??"
    thought "This.. This is Ju Jang Middle School?"
    sara "Soo-ah, what's wrong?"
    soo "..."
    soo "Ah-!"
    thought "That's right..."
    thought "So that's what it was!"
    soo "Hey, why are you misleading people?!"
    sara "Huh??"
    soo "Obviously, the uniforms are different...because it's not my school!"
    sara "What-?"
    soo "The school that I go to is Ju Jang Middle School!!"
    soo "This is the first time I've heard of Zi San Middle School!"
    soo "It looks like my mom misunderstood! Haha-!"
    thought "My mom must've been confused since I recieved the wrong uniform."
    thought "She is wearing the same uniform as me, so she must've thought..."
    soo "Bye then! I'll be going to my school now!"
    soo "Since you're my neighbour, let's get along well~"
    sara "Huh? Soo, Soo-ah! Where are you going?"
    soo "Ju Jang Middle School! It's the school I go to!"
    sara "What...? There's no school like that around here!"
    soo "Of course there is. You just don't know about it."
    soo "Also, aren't you mistaking me for someone else?"
    sara "What are you talking about..."
    soo "Anyways, I'llbe going to school now!"
    soo "Bye!"
    sara "SOO-AH!"
    thought "As expected, there's nothing wrong with my memory!"
    thought "I can't believe I don't have to wear this weird uniform for three years!"
    sara "EEK!"
    sara "Ouch-"
    thought "WHAT THE HELL!"
    thought "...A guy?"
    sara "..."
    thought "His eyes..."
    thought "His eyes are blue...? Is he Korean?"
    thought "Why do these kind of people keep showing up today?"
return