label scene_2:
    "Look over there!"
    "It's one of the Four Heavenly King,s Yoo Cheon Young!"
    "Kya! Eun-Jiho from Four Heavenly Kings is there as well!"
    "Two of the Four Heavenly Kings are seen together?!"
    "Unbelieveable!"
    "Ah..so handsome..."
    npc1 "The Four Heavenly Kings!!"
    npc1 "That sounds so good!"
    npc2 "Right? It fits perfectly!"
    npc1 "The Four Heavenly Kings!"
    npc2 "I can't believe that all of The Four Heavenly Kings are in our class!"
    npc1 "The Four Heavenly Kings!!"
    thought "This... This is not it..."
    npc1 "Is something wrong?"
    thought "I have to get out of this classroom immediately!"
    soo "Ba... Bathroom please..."
    thought "This may be acceptable in novels but not reality!"
    "KYA!!! EUN JI-HO IS COMING THIS WAY!"
    thought "Wha..."
    thought "What?"
    jiho "Who's Sara Park?"
    thought "If it's Sara Park then..."
    sara "..."
    sara "It's me."
    jiho "You're the one that came first place?"
    sara "Yeah, So what?"
    "That arrogant girl! How dare she speak that way to one of The Four Heavenly Kings, Eun Ji-ho!"
    "So rude!"
    jiho "Interesting."
    jiho "Just you wait, I won't go easy on you in the next exam."
    sara "Seriously?"
    sara "Were you actually going easy on me?"
    jiho "Just wait and see."
    "Oh my god..."
    "He's so cool"
    npc1 "Bloody hell! That girl must be crazy!!"
    soo "Yeah.. Crazy.."
    thought "Ge's the weirdesr out of them..."
    woo "Wow! You're amazing!"
    woo "You're the first girl to ever talk to Ji-Ho that way!"
    sara "Ji-Ho?"
    woo "Yep! That guy's name is Eun Ji-Ho!"
    woo "I'm Woo Ju-In!"
    npc1 "How is it possible that she doesn't know who Ji-Ho is?!"
    npc2 "Maybe that's his way of getting his attention"
    woo "Anyway, you're the first person that I've ever seen to win against Ji-Ho!"
    woo "Let's be friends~!"
    thought "HAHA.."
    thought "It feels like I've been thrown into a play..."
    scene black with dissolve
    npc1 "Bye-"
    npc2 "See you tomorrow-"
    thought "I zoned out in class without realizing school ended."

    show saraneutraltalk
    sara "Let's go home Dan-ah."
    soo "Huh?"
    soo "HUUUH?!"
    soo "H-hey wait!"
    sara "Dan-ah you..."
    sara "Since this morning, why have you been acting as if I'm some stranger?"
    thought "Is she upset?"
    sara "Even though I kept staring at you, you just ignored me."
    sara "Why are you acting like this?"
    thought "What about you?"
    thought "She genuinely thinks we're friends..."
    sara "Dan-ah, is this because of what happened a long time ago?"
    soo "What...?"
    thought "SOMETHING HAPPENED???"
    sara "I thought that since you greeted me this morning..."
    sara "...It meant that everything was okay."
    sara "But..."
    sara "Was I mistaken?"
    sara "I acted the way I normally do, but you got even more angry..."
    soo "No, that's not it. I-"
    thought "I don't even know what you're talking about?!"
    sara "Then... Why do you keep avoiding me?"
    sara "Do you hate me now?"
    soo "..."
    soo "No.. I was just a bit confused, that's all."
    soo "How could I hate you..."
    sara "Really? You're really not made at me?"
    soo "Of course not!"
    soo "What could you do to make me hate you?!"
    thought "I don't even know who you are in the first place!!"
    sara "That's a huge relief!"
    sara "Because you're my one and only bestfriend."
    show bg

    sara "Then Dan-I, I'll see you tomorrow!"
    soo "Y-Yeah.."
    soo "...."

    scene bg room

    thought "Ah..."
    thought "What the hell.. happened today..."
    thought "Let's just sleep..."
    scene black with dissolve
    thought "I don't know what's happening but maybe everything will go back to normal once I sleep it off."
    thought "That''s right... And maybe even my uniform will go back to normal..."
    thought "Ji Jon... This ridiculous school name will also go away right?"
    thought "The Four Heavenly Kings and those other things too..."
    scene bg room
    soo "!!"
    soo "..!!"
    thought "I'm in my pajamas!"
    thought "I knew it..!"
    thought "It was all a dream!"
    soo "Mum, you're here-?!"
    mom "What sort of child would sleep all afternoon until now."
    mom "How are you going to sleep at night?"
    soo "Mum listen to this, I fell asleep while reading a web novel yesterday..."
    soo "And I dreamt of the exact same thing that happened in the novel."
    soo "Even both my uniform and school changed."
    soo "And the characters that were also in the novel appeared-"
    soo "It was scary how real it felt."
    soo "And it felt like I was thrown into an unfamiliar world..."
    soo "And a girl I have never met before was my next door neighbour and said we were best friends."
    soo "I got goosebumps all over!"
    mom "You're talking about the girl next door right? Sara?"
    soo "How... How do you know about her?"

    jump chapter_3