label scene_2:
    "Look over there!"
    "It's one of the Four Heavenly King,s Yoo Cheon Young!"
    "Kya! Eun-Jiho from Four Heavenly Kings is there as well!"
    "Two of the Four Heavenly Kings are seen together?!"
    "Unbelieveable!"
    "Ah..so handsome..."
    npc1 "The Four Heavenly Kings!!"
    npc1 "That sounds so good!"
    npc2 "Right? It fits perfectly!"
    npc1 "The Four Heavenly Kings!"
    npc2 "I can't believe that all of The Four Heavenly Kings are in our class!"
    npc1 "The Four Heavenly Kings!!"
    thought "This... This is not it..."
    npc1 "Is something wrong?"
    thought "I have to get out of this classroom immediately!"
    soo "Ba... Bathroom please..."
    thought "This may be acceptable in novels but not reality!"
    "KYA!!! EUN JI-HO IS COMING THIS WAY!"
    thought "Wha..."
    thought "What?"
    jiho "Who's Sara Park?"
    thought "If it's Sara Park then..."
    sara "..."
    sara "It's me."
    jiho "You're the one that came first place?"
    sara "Yeah, So what?"
    "That arrogant girl! How dare she speak that way to one of The Four Heavenly Kings, Eun Ji-ho!"
    "So rude!"
    jiho "Interesting."
    jiho "Just you wait, I won't go easy on you in the next exam."
    sara "Seriously?"
    sara "Were you actually going easy on me?"
    jiho "Just wait and see."
    "Oh my god..."
    "He's so cool"
    npc1 "Bloody hell! That girl must be crazy!!"
    soo "Yeah.. Crazy.."
    thought "Ge's the weirdesr out of them..."
    woo "Wow! You're amazing!"
    woo "You're the first girl to ever talk to Ji-Ho that way!"
    sara "Ji-Ho?"
    woo "Yep! That guy's name is Eun Ji-Ho!"
    woo "I'm Woo Ju-In!"
    npc1 "How is it possible that she doesn't know who Ji-Ho is?!"
    npc2 "Maybe that's his way of getting his attention"
    woo "Anyway, you're the first person that I've ever seen to win against Ji-Ho!"
    woo "Let's be friends~!"
    thought "HAHA.."
    thought "It feels like I've been thrown into a play..."
    scene black with dissolve
    npc1 "Bye-"
    npc2 "See you tomorrow-"
    thought "I zoned out in class without realizing school ended."

