label timeskip:
    "3 Years Later"
    soo "Ah, what... is it mom?"
    soo "Hm-"
    "Wake up."
    thought "Ah, the voice is so soothing."
    thought "But why is their hand so cold..."
    soo "Eun-"
    soo "Eun Ji-Ho! What are you doing here?!"
    jiho "Your mom told me to wake ypou up, so she opened the door for me."
    soo "Ah, mom!"
    mom "I'm busy packing lunch!!!"
    soo "Why're you acting all shy when I've been here several times?"
    soo "D-Do I really look the same when I'm awake and asleep?"
    jiho "You look ugly eiter way?"
    soo "Heh-"
    jiho "..? What?"
    thought "Web Novel's Law Number 3!"
    soo "Hey, you always tell Sara Park that she's ugly too."
    soo "So, does it mean that both Yeoreong and I look the same?"
    jiho "..."
    jiho "Do you really want to hear it?"
    soo "...No thanks."
    soo "Just get out."
    soo "I'm going to get dressed."
    jiho "Got it. So hurry up and come out."
    thought "Ugh... That's no fun."
    thought "As if he weren't the male lead of a web novel already."
    thought "In the end, my plan failed."
    thought "Was it really just a failur?"
    thought "3 years had passed."
    sara "Dan-ah! You're awake?"
    thought "Sara Lee had stayed next door to me and.."
    thought "...She attended the same highschool as me."
    soo "Yeah, you came by?"
    thought "She's still as beautiful as ever."
    thought "Of course, according to the rules of a web novel..."
    thought "...The Four Heavenly Kings alseo enrolled in the same school."
    thought "And today we decided to go on a graduation trip."
    sara "They're waiting for us."
    soo "Then shall we go?"
    thought "Anyhow, this isn't the female lead, Sara Park's story."
    thought "It's mine."

    eunhyeong "Oh! Here they come."
    woo "Huh?"
    soo "Hi~"

    woo "I missed you, mom!"
    soo "Oh my, Ju-In~"
    thought "He's just like a puppy."
    jiho "Hey, you guys."
    sara "You! Don't hug my Dan-I like that!"
    woo "You're interrupting our reunion, you're so mean -"
    jiho "..."
    soo "Guys, let's stop..."
    "..."
    sara "The subway is coming. Let's go."
    soo "Okay."
    thought "Is he still mad about what happened?"
    thought "Well, it's the first time we fought this badly."
    jiho "Hey, Yoo Chunyeong. What was all that about yesterday?"
    chunyeon "I don't want to hear that from someone who just won a bronze."
    jiho "WHAT DOES ME WINNING A BRONZE GOT TO DO WITH ANY OF THIS?"
    soo "They're talking about games again..."
    jiho "Hey! Why do you still have your earphones on when someone is talking to you?"
    thought "If only Eun Ji-Hon didn't open his mouth, he would've been better."
    thought "Maybe my stereotype of him was just too strong..."
    eunhyeong "Ji-Ho."
    eunhyeong "Do you know what happens when you're too loud in a subway?"
    jiho "Huh?"
    jiho "Well there are no passengers except us..."
    eunhyeong "Ah."
    eunhyeong "You've only been riding in limousines so you wouldn't know-"
    jiho "..."
    jiho "I... was wrong."
    soo "..."
    chunyeon "Is something wrong?"
    thought "There's always that one person in a novel that's like that."
    thought "The type of character that is all smiles on the outside."
    thought "But you can never really tell what they're thinking."
    soo "Ah."
    thought "She must've been tired because we woke up early."
    thought "Well, we did come at dawn."
    thought "I'm also tired because I couldn't sleep very well..."
    thought "When the web novel started from that day,"
    thought "I tried my best to avoid Sara Park."
    
    jump flashback

