label timeskip:
    "3 Years Later"
    soo "Ah, what... is it mom?"
    soo "Hm-"
    "Wake up."
    thought "Ah, the voice is so soothing."
    thought "But why is their hand so cold..."
    soo "Eun-"
    soo "Eun Ji-Ho! What are you doing here?!"
    jiho "Your mom told me to wake ypou up, so she opened the door for me."
    soo "Ah, mom!"
    mom "I'm busy packing lunch!!!"
    soo "Why're you acting all shy when I've been here several times?"
    soo "D-Do I really look the same when I'm awake and asleep?"
    jiho "You look ugly eiter way?"
    soo "Heh-"
    jiho "..? What?"
    thought "Web Novel's Law Number 3!"
    soo "Hey, you always tell Sara Park that she's ugly too."
    soo "So, does it mean that both Yeoreong and I look the same?"
    jiho "..."
    jiho "Do you really want to hear it?"
    soo "...No thanks."
    soo "Just get out."
    soo "I'm going to get dressed."
    jiho "Got it. So hurry up and come out."
    thought "Ugh... That's no fun."
    thought "As if he weren't the male lead of a web novel already."
    thought "In the end, my plan failed."
    thought "Was it really just a failur?"
    thought "3 years had passed."
    sara "Dan-ah! You're awake?"
    thought "Sara Lee had stayed next door to me and.."
    thought "...She attended the same highschool as me."
    soo "Yeah, you came by?"
    thought "She's still as beautiful as ever."
    thought "Of course, according to the rules of a web novel..."
    thought "...The Four Heavenly Kings alseo enrolled in the same school."
    thought "And today we decided to go on a graduation trip."
    sara "They're waiting for us."
    soo "Then shall we go?"

    return