label flashback:
    thought "3 years ago. Spring."

    thought "It was not long after I decided to avoid Sara Park."
    thought "I purposefully came out earlier than usual, and now I'm tired."
    "You're leaving early."
    "You've gotten busier since you've entered middle school."
    thought "?!"
    thought "Uh.. uhuh."
    thought "A beautiful but familiar face."
    thought "I REMEMBER."
    thought "He's Sara Park's older brother!"
    thought "Look at their beauty... As expected of the siblings..."
    thought "My eyes are..."
    thought "-NOT BLESSED!"
    thought "THIS IS JUST A CHARACTER FROM A WEB NOVEL!"
    thought "AND THAT'S SARA PARK'S OLDER BROTHER!!"
    thought "This is really annoying..."
    thought "A perfect female lead with a handsome older brother is unbelieveable."

    scene black with fade
    sara "Her Dan-"
    soo "Ah! I need to go to the washroom."
    sara "Dan~!!"
    thought "Until when do I have to keep this up?"
    thought "Is there no other way to avoid her..?"
    "-is so annoying~"
    "Just let her be."
    thought "She's in our class.."
    thought "I think her name was Baek Yeomin."
    yeomin "But still-"
    thought "But what is she so annoyed about?"
    yeomin "Hi, Dan-a~?"
    soo "Uh...? H-hi."
    thought "Why is she acting so friendly?"
    yeomin "Dan~i."
    soo "Yeah?"
    yeomin "Want to be friends?"
    soo "Huh?"
    thought "All of a sudden?"
    thought "Someone I barely talk to wants to get closer?"
    thought "If i get close to someone else..."
    thought "...Won't I eventually end up distancing myself from Sara?"
    soo "Alright!"
    thought "This is it!"
    soo "Let's become friends!"
    sara "Dan-I... She's acting weird since school started."
    sara "Now, she's just openly avoiding me..."
    sara "Just why..."
    sara "..."
    sara "?"
    sara "W-what is it?"
    chungyong "Do you..."
    chunyong "The answer to question 6 on the test?"
    screen black with dissolve
    chunyong "Oh."
    npc "Ch..Chungyoung just smiled...!"
    thought "So he actually does know how to smile."
    thought "Is he only warn towards the female lead?"
    #fact bar
    "orrect answer: He smiled because the question got solved."
    yeomin "It's disgustingly loud."
    soo "?!"
    chungyong "It's all solved."
    yeomin "What's wrong Dan-I?"
    yeomin "Want to go to te shop over there?"
    thought "What?"
    soo "Uh..yes...yeah!"
    yeomin "Let's go."
    sara "Dan-I...?"
    npc "Baek Yeomin always gossips about you."
    npc "She usually talks about you behind your back in the bathroom."
    sara "Why is Dan-I with Baek Yeomin.."
    screen black
    sara "Dan-I, I.."
    soo "Ah, sorry. I need to solve these problems..."
    sara "..."
    jiho "..."
    woo "What do you think of it?"
    jiho "About hat?"
    woo "About Ham Dan-I and Sara Park~"
    woo "Whenever it's break time, it seems like you always look their way?"
    jiho "It is because they openly fight."
    jiho "Ham Dan-I is being too cold."
    jiho "Even thought Sara Park clings onto her, she just pushes her away like it's nothing."
    jiho "If they ever fought..."
    jiho "Wouldn't Ham Dan-I be the cause of it?"
    woo "Hmm~ Why do you think like that?"
    jiho "For the time that I've known Sara Park..."
    jiho "...she doesn't seem like the type to hurt anyone."
    woo "What~?"
    woo "So, you're saying that Ham Dan-I would just hurt others?"
    jiho "My words just came out like that..."
    woo "But isn't it weird?"
    woo "Rther than because of a fight..."
    woo "Doesn't she look like she's scared?"
    "A few days later"
    "What's wrong Sara?"
    "Do you feel sick?"
    sara "...Big Brother"
    sara "I think Dan-I is avoiding me."
    sara "She keeps avoidin having conversations with me..."
    sara "And she's freiends with someone who hates me..."
    sara "Does she not want to be friends with me anymore?"
    "..."
    "Just.. go up to her and talk it out with her."
    "Dan-I has been with us since we were little."
    "I'm sure if you just talk to her, everything will be solved."
    sara "....Um!"
    sara "I'll be right back!"
    screen black with fade
    sara "I have to talk with you!"
    sara "BAEK YEOMIN?!"
    sara "Why is Baek Yeomin in Dan-I's room..."
    sara "Wha-What are you-"
    sara "How'd you get in?"
    